apiVersion: v1
kind: PersistentVolume
metadata:
  # namespace-mountname
  name: gaghir-thesis-k8s-artifacts
spec:
  capacity:
    storage: 100Gi
  nfs:
    server: fs-radar01.tsn.tno.nl
    path: /volume3/k8s/artifacts
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - tcp
    - rw
    - async
    - rsize=32768
    - wsize=32768
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # namespace-mountname-claim
  name: gaghir-thesis-k8s-artifacts-claim
  namespace: gaghir-thesis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: gaghir-thesis-k8s-artifacts
  storageClassName: ''
