apiVersion: v1
kind: PersistentVolume
metadata:
  # namespace-mountname
  name: gaghir-thesis-rtkubtemp
spec:
  capacity:
    storage: 100Gi
  nfs:
    server: fsv-ra21-27.tsn.tno.nl
    path: /ra_express_rtkubtemp
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - tcp
    - rw
    - async
    - rsize=32768
    - wsize=32768
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # namespace-mountname-claim
  name: gaghir-thesis-rtkubtemp-claim
  namespace: gaghir-thesis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: gaghir-thesis-rtkubtemp
  storageClassName: ''