apiVersion: v1
kind: PersistentVolume
metadata:
  # namespace-mountname
  name: gaghir-thesis-tmp
spec:
  capacity:
    storage: 100Gi
  nfs:
    server: fs-radar01.tsn.tno.nl
    path: /volume3/tmp
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - tcp
    - rw
    - async
    - rsize=32768
    - wsize=32768
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # namespace-mountname-claim
  name: gaghir-thesis-tmp-claim
  namespace: gaghir-thesis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: jgaghir-thesis-tmp
  storageClassName: ''
